### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [ankit6889/ColamrAcademy#4]
You did an amazing job on this project. Your HTML and CSS files were really good. You used the right elements and didn’t repeat your code. Visually, you project looked awesome. The extra effort you put into your project really shined. My favorite part is all the animation you added to your page. Your website looks professional and your code is done right. Keep up the good work.

**Comment by ankit6889** [comment]
Thanks for your awesome feedback. Really excited to start my web development career.
